scss_files: "app/assets/stylesheets/**/*.scss"
linters:
  ColorVariable:
    enabled: false
  LeadingZero:
    enabled: true
    style: include_zero
  PropertyCount:
    enabled: false
  QualifyingElement:
    enabled: false
  StringQuotes:
    enabled: true
    style: double_quotes
